### ISSUE TITLE
Initialization of behaviors and events

### ISSUE THREAD

**Issue by paldepind** [paldepind/hareactive#6]
I've been thinking about how best to initialize behaviors and events.

Goals:

* Initialization should only be allowed to happen once
* It should be easy to find where in the view a thing is being initialized

This is what we currently have. Initialization can be found by searching for "name.def".
```js
{click: btnClick.def} = button("Click me")
```

This one looks very non-magical. One would have to find initialization locations by searching for ": name".
```js
button("Click me", {on: {click: btnClick})
```

This one also has no magic. The `def` function (or whatever it should be called) extracts events from the component.
```js
def({click: btnClick}, button("Click me")
```

In this one the `events` list specifies which events to create. But it doesn't work, because the result of the expression whould not be the component but instead the array.
```js
[btnClick.def] = button("Click me", {events: ["click"]})
```

**Comment by limemloh** [comment]
I like the idea of it being non-magical and prefer: 
```js
button("Click me", {on: {click: btnClick})
```
this would work well if we want to implement a HyperScript-like functions where you describe all the properties and settings in an object.
```js
button("click me", { 
  on:{
    click: btnClick
  },
  style: {
    paddingLeft: "5px"
  },
  attributes: {
    disabled
  }
}
```

**Comment by paldepind** [comment]
Good point. It will also work smoothly with JSX which none of the others will. I think we'll pick that one then.

Also, to ensure that a behavior/event can only be hooked into one component, I we could do this: Instead of having a `push` method, the behaviors returned by `declareBehaviors` could have a `getPush` method that returns a push function and throws an error if it is called more than once.
